### ISSUE TITLE
ECP5 TQFP144 devices not supported

### ISSUE THREAD

**Issue by imr** [YosysHQ/prjtrellis#230]
README.md says that all ECP5 devices are supported, but devices.json does not have the TQFP144 package type for the LFE5U-12F, LFE5U-25F, and LFE5U-45 devices.

**Comment by gatecat** [comment]
This should be fixed in https://github.com/YosysHQ/prjtrellis/commit/4d01640911538ff896691d9ca41a2e67e20bc002 and https://github.com/YosysHQ/nextpnr/pull/1193

- Out of curiosity have you actually managed to obtain any parts in this package yet?

**Comment by imr** [comment]
Nope, not yet but distributors have a listed lead time of 20 weeks.
