### ISSUE TITLE
Using SERDES

### ISSUE THREAD

**Issue by gparmeggiani** [YosysHQ/prjtrellis#236]
Hello

I own a ECP5-5G Versa development board. I'm getting started with `prjtrellis` and I got the `versa5g` example to run.

My question is related to SERDES. Is it possible to use the SERDES channels with `projtrellis`? Is there any PCIe or Ethernet example?

**Comment by sprhawk** [comment]
@gparmeggiani Hi, what is the answer ? Could you share it
